vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_ngtk2d5a3shv:
                        id: storleden
                        network:
                            private_network: 192.168.56.88
                            forwarded_port:
                                vflmnfp_4zbfjfn4jegc:
                                    host: '9289'
                                    guest: '22'
                                vflnp_rvqshw7nr098:
                                    host: '35729'
                                    guest: '35729'
                        hostname: local.storleden
                        memory: '2048'
                        cpus: '2'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - htop
        - nfs-common
        - git
        - cifs-utils
        - screen
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '0'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    proxies: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - headers
        - expires
        - vhost_alias
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - common
            - fpm
            - gd
        pear: {  }
        pecl:
            - uploadprogress
            - apcu
            - yaml
    ini:
        display_errors: 'On'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Stockholm
        max_execution_time: '300'
        error_reporting: ALL
        display_startup_errors: 'On'
        html_errors: 'On'
        memory_limit: 512M
        always_populate_raw_post_data: '-1'
        upload_max_filesize: '50M'
        post_max_size: '50M'
        realpath_cache_size: '16M'
        realpath_cache_ttl: '3600'
        opcache.enable: '1'
        opcache.interned_strings_buffer: '24'
        opcache.memory_consumption: '256'
        opcache.max_accelerated_files: '10000'
        opcache.revalidate_freq: '3'
        opcache.fast_shutdown: '1'
        opcache.enable_cli: '1'
        apc.shm_size: '128M'
        apc.ttl: '0'
        apc.gc_ttl: '600'
        apc.enable_cli: '1'
        apc.mmap_file_mask: '/tmp/apc.XXXXXX'
        apc.stat: '1'
        error_log: '/var/log/php_errors.log'
        mbstring.http_input: 'pass'
        mbstring.http_output: 'pass'
        mbstring.func_overload: '0'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_0xn1eunj65w7:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-data
                group: www-data
    composer: '0'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug..profiler_append: '1'
        xdebug..profiler_append: '1'
        xdebug..profiler_enable_trigger: '0'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.idekey: 'PHPSTORM'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 7.1.0
ruby:
    install: '1'
    versions:
        hRDoJFjOLzkH:
            default: '1'
            version: 1.9.3
            gems:
                - sass
                - compass
                - guard
                - livereload
            bundler: '1'
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    npm_packages:
        - yo
        - gulp
        - bower
        - coffee-script
        - jshint
        - csslint
        - eslint
        - nodemon
        - grunt-cli
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: 'mysqlstorleden'
        override_options:
            'mysqld':
                'bind-address': '0.0.0.0'
                'max_allowed_packet': '128M'
                'wait_timeout': '600'
                'query_cache_type': '1'
                'query_cache_size': '128M'
                'query_cache_limit': '2M'
                'innodb_flush_log_at_trx_commit': '2'
                'innodb_lock_wait_timeout': '40'
    adminer: 1
    users:
        mysqlnu_9s2b4eishtao:
            name: devstorleden
            password: 'devstorleden'
    databases:
        mysqlnd_ib1jm8ymdoy0:
            name: dev_project
            sql: ''
    grants:
        mysqlng_xpu9yzdana4i:
            user: devstorleden
            table: '*.*'
            privileges:
                - ALL
mariadb:
    install: '0'
    settings:
        version: '10.0'
        root_password: 'mariadbstorleden'
        override_options:
            'mysqld':
                'bind-address': '0.0.0.0'
                'max_allowed_packet': '128M'
                'wait_timeout': '600'
                'query_cache_type': '1'
                'query_cache_size': '128M'
                'query_cache_limit': '2M'
                'innodb_flush_log_at_trx_commit': '2'
                'innodb_lock_wait_timeout': '40'
    adminer: 1
    users:
        mariadbnu_nid7pavjdjks:
            name: devstorleden
            password: devstorleden
    databases:
        mariadbnd_30ibrqb53wxt:
            name: dev_project
            sql: ''
    grants:
        mariadbng_3xje2xeg3szi:
            user: devstorleden
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: 'psqlstorleden'
    databases:
        postsqlnd_yejpt0oufism:
            dbname: dev_project
            owner: devstorleden
    users:
        postsqlnu_gdro2uymcy5z:
            username: devstorleden
            password: devstorleden
    grants:
        postsqlng_c4yw09cwvlwz:
            role: devstorleden
            db: dev_project
            privilege:
                - ALL
    adminer: 1
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
